#!/usr/bin/env python3
r"""
make_tables.py - turn cp_harness JSON outputs into LaTeX macros + tables, so every number in the
paper comes from one place (the AISTATS AI review checks text/table consistency).

Usage:
  python make_tables.py --alpha 0.1 --out paper/results \
      "ICEWS18|CyGNet|scores/copy_icews18_cp_results.json" \
      "ICEWS18|CENET|scores/cenet_icews18_cp_results.json" \
      "GDELT|CyGNet|scores/copy_gdelt_cp_results.json"

Writes  paper/results_macros.tex   \res{ICEWSeighteen}{CyGNet}{std}{covzs} style macros (see below)
        paper/results_main.tex     main table (Table 1)
        paper/results_drift.tex    Prop. 1 check (Table 2)
        paper/results_oracle.tex   Prop. 4 check (Table 3)
Macro access in the paper:  \R{ICEWS18}{CyGNet}{std}{covzs}  ->  e.g. 6.1
"""
import argparse, json, os

METHOD_NAMES = {"std": "Split CP", "pas": "PAS", "interp": "Interp-Q", "clustered": "Clustered",
                "mond_f": "Mondrian-F", "mond_fr": "Mondrian-FR", "mond_bo": "FRB",
                "fcp": "Feature-norm.", "fnm": "\\textbf{FNM (ours)}"}
ORDER = ["std", "pas", "interp", "clustered", "mond_f", "mond_bo", "fcp", "fnm"]


def pct(x):
    return "--" if x is None else f"{100 * x:.1f}"


def get(d, *ks):
    for k in ks:
        if d is None or k not in d:
            return None
        d = d[k]
    return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("runs", nargs="+", help='"DATASET|SCORER|path.json"')
    ap.add_argument("--alpha", default="0.1")
    ap.add_argument("--out", default="paper/results")
    a = ap.parse_args()
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)

    runs = []
    for spec in a.runs:
        ds, sc, path = spec.split("|")
        runs.append((ds, sc, json.load(open(path))))

    # ---------------- macros: \R{dataset}{scorer}{method}{metric}
    mac = ["% auto-generated by make_tables.py -- do not edit",
           "\\makeatletter",
           "\\providecommand{\\R}[4]{\\@ifundefined{res@#1@#2@#3@#4}{\\textbf{??}}{\\csname res@#1@#2@#3@#4\\endcsname}}"]

    def put(ds, sc, m, k, v):
        mac.append(f"\\expandafter\\def\\csname res@{ds}@{sc}@{m}@{k}\\endcsname{{{v}}}")

    for ds, sc, R in runs:
        B = R["by_alpha"][a.alpha]
        put(ds, sc, "data", "E", f"{R['E']:,}".replace(",", "{,}"))
        put(ds, sc, "data", "Q", f"{R['Q']:,}".replace(",", "{,}"))
        for k, n in enumerate(R["group_sizes"]):
            put(ds, sc, "data", f"gsize{k}", f"{n:,}".replace(",", "{,}"))
        for m, s in B["random_splits"].items():
            put(ds, sc, m, "cov", pct(get(s, "cov", "mean")))
            put(ds, sc, m, "covzs", pct(get(s, "cov_g0", "mean")))
            put(ds, sc, m, "covzssd", pct(get(s, "cov_g0", "std")))
            put(ds, sc, m, "covone", pct(get(s, "cov_g1", "mean")))
            put(ds, sc, m, "covnever", pct(get(s, "cov_fine0", "mean")))   # answers with 0 training occurrences
            put(ds, sc, m, "worstg", pct(get(s, "worst_group_cov", "mean")))
            put(ds, sc, m, "worstf", pct(get(s, "worst_fine_cov", "mean")))
            sz = get(s, "size_mean", "mean")
            put(ds, sc, m, "size", "--" if sz is None else f"{sz:,.0f}".replace(",", "{,}"))
            put(ds, sc, m, "sizefrac", pct(get(s, "size_frac_vocab", "mean")))
            put(ds, sc, m, "insetzs", pct(get(s, "inset_frac_cg0", "mean")))
            ms = B["mixture_shift_split0"].get(m)
            if ms:
                put(ds, sc, m, "mixmin", pct(ms["min"])); put(ds, sc, m, "mixmax", pct(ms["max"]))
        for g, o in B.get("rank_oracle_split0", {}).items():
            put(ds, sc, "oracle", f"{g}frac", pct(o["m_star_frac"]))
        for m, c in B.get("chronological", {}).items():
            put(ds, sc, m, "chcov", pct(c["cov"])); put(ds, sc, m, "chcovzs", pct(c.get("cov_g0")))
            dk = c.get("drift_k")
            if dk:
                for part, v in dk.items():
                    tag = {"novel_seen": "two", "strata3": "three", "fine": "fine"}[part]
                    put(ds, sc, m, f"dk{tag}corr", "--" if v["corr"] is None else f"{v['corr']:.2f}")
                    put(ds, sc, m, f"dk{tag}mae", "--" if v["mae"] is None else f"{100*v['mae']:.1f}")
                    put(ds, sc, m, f"dk{tag}n", str(v["n_windows"]))
            dr = c.get("drift")
            if dr:
                put(ds, sc, m, "picals", pct(dr["pi_cal"])); put(ds, sc, m, "pitest", pct(dr["pi_test"]))
                put(ds, sc, m, "driftcorr", "--" if dr["corr_obs_vs_pred"] is None else f"{dr['corr_obs_vs_pred']:.2f}")
                put(ds, sc, m, "driftmae", "--" if dr["mae_obs_vs_pred"] is None else f"{100*dr['mae_obs_vs_pred']:.1f}")
    mac.append("\\makeatother")
    open(a.out + "_macros.tex", "w").write("\n".join(mac) + "\n")

    # ---------------- Table 1: main results
    L = ["% auto-generated", "\\begin{tabular}{ll rrrrr}", "\\toprule",
         "Data / scorer & Method & Cov. & Cov.$_{\\text{zs}}$ & Worst bin & $|C|$ & $|C|/|\\mathcal{E}|$ \\\\",
         "\\midrule"]
    for i, (ds, sc, R) in enumerate(runs):
        S = R["by_alpha"][a.alpha]["random_splits"]
        ms = [m for m in ORDER if m in S]
        for j, m in enumerate(ms):
            s = S[m]
            lead = f"\\multirow{{{len(ms)}}}{{*}}{{\\shortstack[l]{{{ds}\\\\{sc}}}}}" if j == 0 else ""
            zs = pct(get(s, "cov_g0", "mean")); zsd = pct(get(s, "cov_g0", "std"))
            sz = get(s, "size_mean", "mean")
            L.append(f"{lead} & {METHOD_NAMES[m]} & {pct(get(s,'cov','mean'))} & {zs}\\,{{\\scriptsize$\\pm${zsd}}} & "
                     f"{pct(get(s,'worst_fine_cov','mean'))} & {'--' if sz is None else f'{sz:,.0f}'} & "
                     f"{pct(get(s,'size_frac_vocab','mean'))} \\\\")
        L.append("\\midrule" if i < len(runs) - 1 else "\\bottomrule")
    L.append("\\end{tabular}")
    open(a.out + "_main.tex", "w").write("\n".join(L) + "\n")

    # ---------------- Table 2: Prop. 1 drift check (split CP, chronological)
    L = ["% auto-generated", "\\begin{tabular}{l rrrr rr}", "\\toprule",
         "Data & $\\pi^{\\text{cal}}_0$ & $\\pi^{\\text{test}}_0$ & $c_{\\text{seen}}$ & $c_0$ & $r_{2}$ & $r_{\\text{fine}}$ (MAE) \\\\",
         "\\midrule"]
    for ds, sc, R in runs:
        dr = get(R["by_alpha"][a.alpha], "chronological", "std", "drift")
        if not dr:
            continue
        dk = get(R["by_alpha"][a.alpha], "chronological", "std", "drift_k") or {}
        f2 = lambda v: "--" if v is None else f"{v:.2f}"
        two, fine = dk.get("novel_seen", {}), dk.get("fine", {})
        fm = "" if fine.get("mae") is None else f" ({100*fine['mae']:.1f})"
        L.append(f"{ds} & {pct(dr['pi_cal'])} & {pct(dr['pi_test'])} & {pct(dr['cov_seen'])} & "
                 f"{pct(dr['cov_novel'])} & {f2(two.get('corr'))} & {f2(fine.get('corr'))}{fm} \\\\")
    L += ["\\bottomrule", "\\end{tabular}"]
    open(a.out + "_drift.tex", "w").write("\n".join(L) + "\n")

    # ---------------- Table 3: Prop. 4 oracle vs Mondrian in-group mass (zero-shot stratum)
    L = ["% auto-generated", "\\begin{tabular}{l rrr}", "\\toprule",
         "Data & $|\\mathcal{E}_0|$ & $m^\\star_0/|\\mathcal{E}_0|$ & Mondrian $|C\\cap\\mathcal{E}_0|/|\\mathcal{E}_0|$ \\\\",
         "\\midrule"]
    for ds, sc, R in runs:
        B = R["by_alpha"][a.alpha]
        o = get(B, "rank_oracle_split0", "g0")
        mf = get(B, "random_splits", "mond_f", "inset_frac_cg0", "mean")
        if o:
            L.append(f"{ds} & {o['group_size']:,} & {pct(o['m_star_frac'])} & {pct(mf)} \\\\")
    L += ["\\bottomrule", "\\end{tabular}"]
    open(a.out + "_oracle.tex", "w").write("\n".join(L) + "\n")
    print("wrote", a.out + "_{macros,main,drift,oracle}.tex")


if __name__ == "__main__":
    main()
