#!/usr/bin/env python3
"""make_rolling_table.py OUT "DATA|SCORER|path_rolling.json" ...  -> OUT.tex (table) + OUT_macros.tex"""
import sys, json
NAMES = {"std": "Split CP", "aci": "ACI", "mond_f": "Mondrian-F", "aci_mond": "Mondrian-ACI",
         "fcp": "Feature-norm.", "fnm": "FNM", "da_fnm": "\\textbf{DA-FNM}"}
ORDER = ["std", "aci", "mond_f", "aci_mond", "fcp", "fnm", "da_fnm"]
out = sys.argv[1]
p = lambda x: "--" if x is None else f"{100*x:.1f}"
L = ["% auto-generated by make_rolling_table.py", "\\begin{tabular}{ll rr rr rr r}", "\\toprule",
     " & & \\multicolumn{2}{c}{Cov.} & \\multicolumn{2}{c}{Cov.$_\\text{zs}$} & \\multicolumn{2}{c}{Worst bin} & \\\\",
     "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}",
     "Data / scorer & Method & mean & min & mean & min & mean & min & $|C|/|\\mathcal{E}|$ \\\\", "\\midrule"]
mac = ["% auto-generated", "\\makeatletter",
       "\\providecommand{\\RO}[4]{\\@ifundefined{rol@#1@#2@#3@#4}{\\textbf{??}}{\\csname rol@#1@#2@#3@#4\\endcsname}}"]
specs = sys.argv[2:]
for i, spec in enumerate(specs):
    ds, sc, path = spec.split("|"); R = json.load(open(path)); S = R["summary"]
    ms = [m for m in ORDER if m in S]
    nw = len(R["windows"][ms[0]])
    for j, m in enumerate(ms):
        s = S[m]
        lead = f"\\multirow{{{len(ms)}}}{{*}}{{\\shortstack[l]{{{ds}\\\\{sc}\\\\({nw} windows)}}}}" if j == 0 else ""
        L.append(f"{lead} & {NAMES[m]} & {p(s['cov'][0])} & {p(s['cov'][1])} & {p(s['cov_g0'][0])} & {p(s['cov_g0'][1])} & "
                 f"{p(s['worst_fine'][0])} & {p(s['worst_fine'][1])} & {p(s['size_frac'][0])} \\\\")
        for key, idx, tag in [("cov", 0, "cov"), ("cov", 1, "covmin"), ("cov_g0", 0, "covzs"), ("cov_g0", 1, "covzsmin"),
                              ("worst_fine", 0, "worst"), ("worst_fine", 1, "worstmin"), ("size_frac", 0, "size")]:
            mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@{m}@{tag}\\endcsname{{{p(s[key][idx])}}}")
        if "worst_g" in s:
            mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@{m}@worstg\\endcsname{{{p(s['worst_g'][0])}}}")
            mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@{m}@worstgmin\\endcsname{{{p(s['worst_g'][1])}}}")
    mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@data@nw\\endcsname{{{nw}}}")
    pis = [w["pi0"] for w in R["windows"][ms[0]]]
    mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@data@pimin\\endcsname{{{p(min(pis))}}}")
    mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@data@pimax\\endcsname{{{p(max(pis))}}}")
    ks = [max(w["ks"].values()) for w in R["windows"].get("fnm", []) if w.get("ks")]
    ks0 = [w["ks"]["g0"] for w in R["windows"].get("fnm", []) if w.get("ks") and "g0" in w["ks"]]
    if ks:
        mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@data@ksmax\\endcsname{{{max(ks):.2f}}}")
    if ks0:
        mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@data@kszeromean\\endcsname{{{sum(ks0)/len(ks0):.2f}}}")
        mac.append(f"\\expandafter\\def\\csname rol@{ds}@{sc}@data@kszeromax\\endcsname{{{max(ks0):.2f}}}")
    L.append("\\midrule" if i < len(specs) - 1 else "\\bottomrule")
L.append("\\end{tabular}")
mac.append("\\makeatother")
open(out + ".tex", "w").write("\n".join(L) + "\n")
open(out + "_macros.tex", "w").write("\n".join(mac) + "\n")
print("wrote", out + ".tex", out + "_macros.tex")
